// Comprehensive Timezone Cities Database
// Over 500 cities worldwide organized by region

window.TimezoneCities = {
  // ==========================================
  // NORTH AMERICA - USA (100+ cities)
  // ==========================================
  // Eastern Time
  'New York': 'America/New_York',
  'Philadelphia': 'America/New_York',
  'Boston': 'America/New_York',
  'Washington DC': 'America/New_York',
  'Atlanta': 'America/New_York',
  'Miami': 'America/New_York',
  'Tampa': 'America/New_York',
  'Orlando': 'America/New_York',
  'Jacksonville': 'America/New_York',
  'Charlotte': 'America/New_York',
  'Raleigh': 'America/New_York',
  'Baltimore': 'America/New_York',
  'Pittsburgh': 'America/New_York',
  'Cleveland': 'America/New_York',
  'Columbus': 'America/New_York',
  'Cincinnati': 'America/New_York',
  'Buffalo': 'America/New_York',
  'Richmond': 'America/New_York',
  'Virginia Beach': 'America/New_York',
  'Newark': 'America/New_York',
  'Providence': 'America/New_York',
  'Hartford': 'America/New_York',
  'New Haven': 'America/New_York',
  'Savannah': 'America/New_York',
  'Charleston SC': 'America/New_York',
  'Fort Lauderdale': 'America/New_York',
  'West Palm Beach': 'America/New_York',
  'Key West': 'America/New_York',

  // Central Time
  'Chicago': 'America/Chicago',
  'Houston': 'America/Chicago',
  'Dallas': 'America/Chicago',
  'San Antonio': 'America/Chicago',
  'Austin': 'America/Chicago',
  'Fort Worth': 'America/Chicago',
  'Nashville': 'America/Chicago',
  'Memphis': 'America/Chicago',
  'Milwaukee': 'America/Chicago',
  'Minneapolis': 'America/Chicago',
  'St. Paul': 'America/Chicago',
  'Kansas City': 'America/Chicago',
  'St. Louis': 'America/Chicago',
  'New Orleans': 'America/Chicago',
  'Oklahoma City': 'America/Chicago',
  'Tulsa': 'America/Chicago',
  'Omaha': 'America/Chicago',
  'Wichita': 'America/Chicago',
  'Little Rock': 'America/Chicago',
  'Birmingham': 'America/Chicago',
  'Mobile': 'America/Chicago',
  'Baton Rouge': 'America/Chicago',
  'Des Moines': 'America/Chicago',
  'Madison': 'America/Chicago',
  'Green Bay': 'America/Chicago',
  'Corpus Christi': 'America/Chicago',
  'El Paso': 'America/Denver',
  'Lubbock': 'America/Chicago',

  // Mountain Time
  'Denver': 'America/Denver',
  'Phoenix': 'America/Phoenix',
  'Albuquerque': 'America/Denver',
  'Salt Lake City': 'America/Denver',
  'Tucson': 'America/Phoenix',
  'Colorado Springs': 'America/Denver',
  'Mesa': 'America/Phoenix',
  'Boise': 'America/Boise',
  'Scottsdale': 'America/Phoenix',
  'Aurora CO': 'America/Denver',
  'Santa Fe': 'America/Denver',
  'Provo': 'America/Denver',
  'Cheyenne': 'America/Denver',
  'Billings': 'America/Denver',
  'Missoula': 'America/Denver',
  'Flagstaff': 'America/Phoenix',

  // Pacific Time
  'Los Angeles': 'America/Los_Angeles',
  'San Francisco': 'America/Los_Angeles',
  'San Diego': 'America/Los_Angeles',
  'San Jose': 'America/Los_Angeles',
  'Seattle': 'America/Los_Angeles',
  'Portland': 'America/Los_Angeles',
  'Las Vegas': 'America/Los_Angeles',
  'Sacramento': 'America/Los_Angeles',
  'Fresno': 'America/Los_Angeles',
  'Long Beach': 'America/Los_Angeles',
  'Oakland': 'America/Los_Angeles',
  'Bakersfield': 'America/Los_Angeles',
  'Anaheim': 'America/Los_Angeles',
  'Santa Ana': 'America/Los_Angeles',
  'Riverside': 'America/Los_Angeles',
  'Stockton': 'America/Los_Angeles',
  'Irvine': 'America/Los_Angeles',
  'Spokane': 'America/Los_Angeles',
  'Tacoma': 'America/Los_Angeles',
  'Reno': 'America/Los_Angeles',
  'Pasadena': 'America/Los_Angeles',
  'Santa Barbara': 'America/Los_Angeles',
  'Palm Springs': 'America/Los_Angeles',
  'Eugene': 'America/Los_Angeles',
  'Salem': 'America/Los_Angeles',

  // Alaska & Hawaii
  'Honolulu': 'Pacific/Honolulu',
  'Anchorage': 'America/Anchorage',
  'Fairbanks': 'America/Anchorage',
  'Juneau': 'America/Juneau',
  'Maui': 'Pacific/Honolulu',
  'Kona': 'Pacific/Honolulu',

  // Detroit (Eastern but notable)
  'Detroit': 'America/Detroit',
  'Grand Rapids': 'America/Detroit',
  'Ann Arbor': 'America/Detroit',
  'Indianapolis': 'America/Indiana/Indianapolis',
  'Louisville': 'America/Kentucky/Louisville',

  // ==========================================
  // CANADA (40+ cities)
  // ==========================================
  'Toronto': 'America/Toronto',
  'Montreal': 'America/Montreal',
  'Vancouver': 'America/Vancouver',
  'Calgary': 'America/Edmonton',
  'Edmonton': 'America/Edmonton',
  'Ottawa': 'America/Toronto',
  'Winnipeg': 'America/Winnipeg',
  'Quebec City': 'America/Montreal',
  'Hamilton': 'America/Toronto',
  'Halifax': 'America/Halifax',
  'Victoria': 'America/Vancouver',
  'Saskatoon': 'America/Regina',
  'Regina': 'America/Regina',
  'St. Johns NL': 'America/St_Johns',
  'Kelowna': 'America/Vancouver',
  'Whistler': 'America/Vancouver',
  'Banff': 'America/Edmonton',
  'Niagara Falls': 'America/Toronto',
  'London ON': 'America/Toronto',
  'Windsor': 'America/Toronto',
  'Charlottetown': 'America/Halifax',
  'Fredericton': 'America/Moncton',
  'Yellowknife': 'America/Yellowknife',
  'Whitehorse': 'America/Whitehorse',

  // ==========================================
  // MEXICO & CENTRAL AMERICA (25+ cities)
  // ==========================================
  'Mexico City': 'America/Mexico_City',
  'Guadalajara': 'America/Mexico_City',
  'Monterrey': 'America/Monterrey',
  'Cancun': 'America/Cancun',
  'Tijuana': 'America/Tijuana',
  'Puebla': 'America/Mexico_City',
  'Merida': 'America/Merida',
  'Acapulco': 'America/Mexico_City',
  'Puerto Vallarta': 'America/Mexico_City',
  'Los Cabos': 'America/Mazatlan',
  'Oaxaca': 'America/Mexico_City',
  'Playa del Carmen': 'America/Cancun',
  'Guatemala City': 'America/Guatemala',
  'San Salvador': 'America/El_Salvador',
  'Tegucigalpa': 'America/Tegucigalpa',
  'Managua': 'America/Managua',
  'San Jose CR': 'America/Costa_Rica',
  'Panama City': 'America/Panama',
  'Belize City': 'America/Belize',

  // ==========================================
  // CARIBBEAN (20+ cities)
  // ==========================================
  'Havana': 'America/Havana',
  'Santo Domingo': 'America/Santo_Domingo',
  'San Juan': 'America/Puerto_Rico',
  'Kingston': 'America/Jamaica',
  'Nassau': 'America/Nassau',
  'Port-au-Prince': 'America/Port-au-Prince',
  'Bridgetown': 'America/Barbados',
  'Port of Spain': 'America/Port_of_Spain',
  'St. Thomas': 'America/Virgin',
  'Aruba': 'America/Aruba',
  'Curacao': 'America/Curacao',
  'Grand Cayman': 'America/Cayman',
  'Bermuda': 'Atlantic/Bermuda',
  'Punta Cana': 'America/Santo_Domingo',

  // ==========================================
  // SOUTH AMERICA (40+ cities)
  // ==========================================
  'Sao Paulo': 'America/Sao_Paulo',
  'Rio de Janeiro': 'America/Sao_Paulo',
  'Buenos Aires': 'America/Argentina/Buenos_Aires',
  'Lima': 'America/Lima',
  'Bogota': 'America/Bogota',
  'Santiago': 'America/Santiago',
  'Caracas': 'America/Caracas',
  'Medellin': 'America/Bogota',
  'Cali': 'America/Bogota',
  'Cartagena': 'America/Bogota',
  'Quito': 'America/Guayaquil',
  'Guayaquil': 'America/Guayaquil',
  'Montevideo': 'America/Montevideo',
  'La Paz': 'America/La_Paz',
  'Asuncion': 'America/Asuncion',
  'Brasilia': 'America/Sao_Paulo',
  'Salvador': 'America/Bahia',
  'Fortaleza': 'America/Fortaleza',
  'Belo Horizonte': 'America/Sao_Paulo',
  'Manaus': 'America/Manaus',
  'Recife': 'America/Recife',
  'Curitiba': 'America/Sao_Paulo',
  'Porto Alegre': 'America/Sao_Paulo',
  'Mendoza': 'America/Argentina/Mendoza',
  'Cordoba': 'America/Argentina/Cordoba',
  'Cusco': 'America/Lima',
  'Machu Picchu': 'America/Lima',
  'Galapagos': 'Pacific/Galapagos',
  'Easter Island': 'Pacific/Easter',

  // ==========================================
  // EUROPE - WESTERN (60+ cities)
  // ==========================================
  'London': 'Europe/London',
  'Manchester': 'Europe/London',
  'Birmingham UK': 'Europe/London',
  'Liverpool': 'Europe/London',
  'Edinburgh': 'Europe/London',
  'Glasgow': 'Europe/London',
  'Belfast': 'Europe/London',
  'Cardiff': 'Europe/London',
  'Bristol': 'Europe/London',
  'Leeds': 'Europe/London',
  'Newcastle': 'Europe/London',
  'Dublin': 'Europe/Dublin',
  'Cork': 'Europe/Dublin',
  'Galway': 'Europe/Dublin',

  'Paris': 'Europe/Paris',
  'Lyon': 'Europe/Paris',
  'Marseille': 'Europe/Paris',
  'Nice': 'Europe/Paris',
  'Toulouse': 'Europe/Paris',
  'Bordeaux': 'Europe/Paris',
  'Strasbourg': 'Europe/Paris',
  'Lille': 'Europe/Paris',
  'Nantes': 'Europe/Paris',
  'Cannes': 'Europe/Paris',
  'Monaco': 'Europe/Monaco',

  'Berlin': 'Europe/Berlin',
  'Munich': 'Europe/Berlin',
  'Frankfurt': 'Europe/Berlin',
  'Hamburg': 'Europe/Berlin',
  'Cologne': 'Europe/Berlin',
  'Dusseldorf': 'Europe/Berlin',
  'Stuttgart': 'Europe/Berlin',
  'Dresden': 'Europe/Berlin',
  'Leipzig': 'Europe/Berlin',
  'Hannover': 'Europe/Berlin',
  'Nuremberg': 'Europe/Berlin',

  'Amsterdam': 'Europe/Amsterdam',
  'Rotterdam': 'Europe/Amsterdam',
  'The Hague': 'Europe/Amsterdam',
  'Brussels': 'Europe/Brussels',
  'Antwerp': 'Europe/Brussels',
  'Luxembourg': 'Europe/Luxembourg',

  'Zurich': 'Europe/Zurich',
  'Geneva': 'Europe/Zurich',
  'Basel': 'Europe/Zurich',
  'Bern': 'Europe/Zurich',
  'Lucerne': 'Europe/Zurich',

  'Vienna': 'Europe/Vienna',
  'Salzburg': 'Europe/Vienna',
  'Innsbruck': 'Europe/Vienna',

  // ==========================================
  // EUROPE - SOUTHERN (40+ cities)
  // ==========================================
  'Madrid': 'Europe/Madrid',
  'Barcelona': 'Europe/Madrid',
  'Valencia': 'Europe/Madrid',
  'Seville': 'Europe/Madrid',
  'Malaga': 'Europe/Madrid',
  'Bilbao': 'Europe/Madrid',
  'Granada': 'Europe/Madrid',
  'Ibiza': 'Europe/Madrid',
  'Mallorca': 'Europe/Madrid',
  'Tenerife': 'Atlantic/Canary',
  'Las Palmas': 'Atlantic/Canary',

  'Lisbon': 'Europe/Lisbon',
  'Porto': 'Europe/Lisbon',
  'Faro': 'Europe/Lisbon',
  'Madeira': 'Atlantic/Madeira',
  'Azores': 'Atlantic/Azores',

  'Rome': 'Europe/Rome',
  'Milan': 'Europe/Rome',
  'Florence': 'Europe/Rome',
  'Venice': 'Europe/Rome',
  'Naples': 'Europe/Rome',
  'Turin': 'Europe/Rome',
  'Bologna': 'Europe/Rome',
  'Genoa': 'Europe/Rome',
  'Palermo': 'Europe/Rome',
  'Verona': 'Europe/Rome',
  'Pisa': 'Europe/Rome',
  'Amalfi': 'Europe/Rome',
  'Capri': 'Europe/Rome',

  'Athens': 'Europe/Athens',
  'Thessaloniki': 'Europe/Athens',
  'Mykonos': 'Europe/Athens',
  'Santorini': 'Europe/Athens',
  'Crete': 'Europe/Athens',
  'Rhodes': 'Europe/Athens',
  'Corfu': 'Europe/Athens',

  'Malta': 'Europe/Malta',
  'Cyprus': 'Asia/Nicosia',

  // ==========================================
  // EUROPE - NORTHERN (25+ cities)
  // ==========================================
  'Stockholm': 'Europe/Stockholm',
  'Gothenburg': 'Europe/Stockholm',
  'Malmo': 'Europe/Stockholm',
  'Oslo': 'Europe/Oslo',
  'Bergen': 'Europe/Oslo',
  'Tromso': 'Europe/Oslo',
  'Copenhagen': 'Europe/Copenhagen',
  'Aarhus': 'Europe/Copenhagen',
  'Helsinki': 'Europe/Helsinki',
  'Tampere': 'Europe/Helsinki',
  'Turku': 'Europe/Helsinki',
  'Reykjavik': 'Atlantic/Reykjavik',

  // ==========================================
  // EUROPE - EASTERN (50+ cities)
  // ==========================================
  'Moscow': 'Europe/Moscow',
  'St. Petersburg': 'Europe/Moscow',
  'Kazan': 'Europe/Moscow',
  'Sochi': 'Europe/Moscow',
  'Yekaterinburg': 'Asia/Yekaterinburg',
  'Novosibirsk': 'Asia/Novosibirsk',
  'Vladivostok': 'Asia/Vladivostok',

  'Warsaw': 'Europe/Warsaw',
  'Krakow': 'Europe/Warsaw',
  'Gdansk': 'Europe/Warsaw',
  'Wroclaw': 'Europe/Warsaw',
  'Poznan': 'Europe/Warsaw',

  'Prague': 'Europe/Prague',
  'Brno': 'Europe/Prague',
  'Budapest': 'Europe/Budapest',
  'Bucharest': 'Europe/Bucharest',
  'Sofia': 'Europe/Sofia',

  'Istanbul': 'Europe/Istanbul',
  'Ankara': 'Europe/Istanbul',
  'Izmir': 'Europe/Istanbul',
  'Antalya': 'Europe/Istanbul',
  'Bodrum': 'Europe/Istanbul',
  'Cappadocia': 'Europe/Istanbul',

  'Kyiv': 'Europe/Kyiv',
  'Lviv': 'Europe/Kyiv',
  'Odesa': 'Europe/Kyiv',
  'Minsk': 'Europe/Minsk',

  'Belgrade': 'Europe/Belgrade',
  'Zagreb': 'Europe/Zagreb',
  'Split': 'Europe/Zagreb',
  'Dubrovnik': 'Europe/Zagreb',
  'Ljubljana': 'Europe/Ljubljana',
  'Bratislava': 'Europe/Bratislava',

  'Riga': 'Europe/Riga',
  'Vilnius': 'Europe/Vilnius',
  'Tallinn': 'Europe/Tallinn',

  'Sarajevo': 'Europe/Sarajevo',
  'Skopje': 'Europe/Skopje',
  'Tirana': 'Europe/Tirane',
  'Podgorica': 'Europe/Podgorica',
  'Pristina': 'Europe/Belgrade',
  'Chisinau': 'Europe/Chisinau',

  // ==========================================
  // MIDDLE EAST (40+ cities)
  // ==========================================
  'Dubai': 'Asia/Dubai',
  'Abu Dhabi': 'Asia/Dubai',
  'Sharjah': 'Asia/Dubai',
  'Tel Aviv': 'Asia/Jerusalem',
  'Jerusalem': 'Asia/Jerusalem',
  'Haifa': 'Asia/Jerusalem',
  'Riyadh': 'Asia/Riyadh',
  'Jeddah': 'Asia/Riyadh',
  'Mecca': 'Asia/Riyadh',
  'Medina': 'Asia/Riyadh',
  'Doha': 'Asia/Qatar',
  'Kuwait City': 'Asia/Kuwait',
  'Muscat': 'Asia/Muscat',
  'Manama': 'Asia/Bahrain',
  'Amman': 'Asia/Amman',
  'Petra': 'Asia/Amman',
  'Beirut': 'Asia/Beirut',
  'Damascus': 'Asia/Damascus',
  'Baghdad': 'Asia/Baghdad',
  'Erbil': 'Asia/Baghdad',
  'Tehran': 'Asia/Tehran',
  'Isfahan': 'Asia/Tehran',
  'Shiraz': 'Asia/Tehran',
  'Tabriz': 'Asia/Tehran',
  'Sana\'a': 'Asia/Aden',
  'Aden': 'Asia/Aden',

  // ==========================================
  // AFRICA (50+ cities)
  // ==========================================
  'Cairo': 'Africa/Cairo',
  'Alexandria': 'Africa/Cairo',
  'Luxor': 'Africa/Cairo',
  'Sharm El Sheikh': 'Africa/Cairo',
  'Hurghada': 'Africa/Cairo',

  'Johannesburg': 'Africa/Johannesburg',
  'Cape Town': 'Africa/Johannesburg',
  'Durban': 'Africa/Johannesburg',
  'Pretoria': 'Africa/Johannesburg',
  'Port Elizabeth': 'Africa/Johannesburg',

  'Lagos': 'Africa/Lagos',
  'Abuja': 'Africa/Lagos',
  'Nairobi': 'Africa/Nairobi',
  'Mombasa': 'Africa/Nairobi',
  'Casablanca': 'Africa/Casablanca',
  'Marrakech': 'Africa/Casablanca',
  'Fes': 'Africa/Casablanca',
  'Tangier': 'Africa/Casablanca',
  'Rabat': 'Africa/Casablanca',

  'Accra': 'Africa/Accra',
  'Addis Ababa': 'Africa/Addis_Ababa',
  'Dar es Salaam': 'Africa/Dar_es_Salaam',
  'Zanzibar': 'Africa/Dar_es_Salaam',
  'Kampala': 'Africa/Kampala',
  'Kigali': 'Africa/Kigali',

  'Tunis': 'Africa/Tunis',
  'Algiers': 'Africa/Algiers',
  'Tripoli': 'Africa/Tripoli',
  'Dakar': 'Africa/Dakar',
  'Abidjan': 'Africa/Abidjan',
  'Kinshasa': 'Africa/Kinshasa',
  'Luanda': 'Africa/Luanda',
  'Harare': 'Africa/Harare',
  'Victoria Falls': 'Africa/Harare',
  'Windhoek': 'Africa/Windhoek',
  'Maputo': 'Africa/Maputo',
  'Antananarivo': 'Indian/Antananarivo',
  'Mauritius': 'Indian/Mauritius',
  'Seychelles': 'Indian/Mahe',

  // ==========================================
  // SOUTH ASIA (40+ cities)
  // ==========================================
  'Mumbai': 'Asia/Kolkata',
  'Delhi': 'Asia/Kolkata',
  'New Delhi': 'Asia/Kolkata',
  'Bangalore': 'Asia/Kolkata',
  'Chennai': 'Asia/Kolkata',
  'Hyderabad': 'Asia/Kolkata',
  'Kolkata': 'Asia/Kolkata',
  'Pune': 'Asia/Kolkata',
  'Ahmedabad': 'Asia/Kolkata',
  'Jaipur': 'Asia/Kolkata',
  'Goa': 'Asia/Kolkata',
  'Agra': 'Asia/Kolkata',
  'Varanasi': 'Asia/Kolkata',
  'Udaipur': 'Asia/Kolkata',
  'Kerala': 'Asia/Kolkata',
  'Amritsar': 'Asia/Kolkata',
  'Chandigarh': 'Asia/Kolkata',
  'Lucknow': 'Asia/Kolkata',
  'Surat': 'Asia/Kolkata',
  'Indore': 'Asia/Kolkata',
  'Nagpur': 'Asia/Kolkata',

  'Karachi': 'Asia/Karachi',
  'Lahore': 'Asia/Karachi',
  'Islamabad': 'Asia/Karachi',
  'Rawalpindi': 'Asia/Karachi',
  'Faisalabad': 'Asia/Karachi',

  'Dhaka': 'Asia/Dhaka',
  'Chittagong': 'Asia/Dhaka',
  'Colombo': 'Asia/Colombo',
  'Kandy': 'Asia/Colombo',
  'Kathmandu': 'Asia/Kathmandu',
  'Pokhara': 'Asia/Kathmandu',
  'Thimphu': 'Asia/Thimphu',
  'Male': 'Indian/Maldives',

  // ==========================================
  // SOUTHEAST ASIA (40+ cities)
  // ==========================================
  'Singapore': 'Asia/Singapore',
  'Bangkok': 'Asia/Bangkok',
  'Phuket': 'Asia/Bangkok',
  'Chiang Mai': 'Asia/Bangkok',
  'Pattaya': 'Asia/Bangkok',
  'Krabi': 'Asia/Bangkok',
  'Koh Samui': 'Asia/Bangkok',

  'Jakarta': 'Asia/Jakarta',
  'Bali': 'Asia/Makassar',
  'Surabaya': 'Asia/Jakarta',
  'Bandung': 'Asia/Jakarta',
  'Yogyakarta': 'Asia/Jakarta',
  'Lombok': 'Asia/Makassar',

  'Kuala Lumpur': 'Asia/Kuala_Lumpur',
  'Penang': 'Asia/Kuala_Lumpur',
  'Langkawi': 'Asia/Kuala_Lumpur',
  'Kota Kinabalu': 'Asia/Kuala_Lumpur',

  'Manila': 'Asia/Manila',
  'Cebu': 'Asia/Manila',
  'Boracay': 'Asia/Manila',
  'Palawan': 'Asia/Manila',

  'Ho Chi Minh City': 'Asia/Ho_Chi_Minh',
  'Hanoi': 'Asia/Ho_Chi_Minh',
  'Da Nang': 'Asia/Ho_Chi_Minh',
  'Hoi An': 'Asia/Ho_Chi_Minh',
  'Nha Trang': 'Asia/Ho_Chi_Minh',
  'Ha Long Bay': 'Asia/Ho_Chi_Minh',

  'Phnom Penh': 'Asia/Phnom_Penh',
  'Siem Reap': 'Asia/Phnom_Penh',
  'Vientiane': 'Asia/Vientiane',
  'Luang Prabang': 'Asia/Vientiane',
  'Yangon': 'Asia/Yangon',
  'Bagan': 'Asia/Yangon',
  'Brunei': 'Asia/Brunei',

  // ==========================================
  // EAST ASIA (50+ cities)
  // ==========================================
  'Tokyo': 'Asia/Tokyo',
  'Osaka': 'Asia/Tokyo',
  'Kyoto': 'Asia/Tokyo',
  'Yokohama': 'Asia/Tokyo',
  'Nagoya': 'Asia/Tokyo',
  'Sapporo': 'Asia/Tokyo',
  'Fukuoka': 'Asia/Tokyo',
  'Kobe': 'Asia/Tokyo',
  'Hiroshima': 'Asia/Tokyo',
  'Nara': 'Asia/Tokyo',
  'Okinawa': 'Asia/Tokyo',
  'Hakone': 'Asia/Tokyo',
  'Nikko': 'Asia/Tokyo',

  'Seoul': 'Asia/Seoul',
  'Busan': 'Asia/Seoul',
  'Incheon': 'Asia/Seoul',
  'Jeju': 'Asia/Seoul',
  'Daegu': 'Asia/Seoul',
  'Gyeongju': 'Asia/Seoul',

  'Beijing': 'Asia/Shanghai',
  'Shanghai': 'Asia/Shanghai',
  'Hong Kong': 'Asia/Hong_Kong',
  'Shenzhen': 'Asia/Shanghai',
  'Guangzhou': 'Asia/Shanghai',
  'Chengdu': 'Asia/Shanghai',
  'Hangzhou': 'Asia/Shanghai',
  'Xian': 'Asia/Shanghai',
  'Nanjing': 'Asia/Shanghai',
  'Suzhou': 'Asia/Shanghai',
  'Chongqing': 'Asia/Shanghai',
  'Wuhan': 'Asia/Shanghai',
  'Tianjin': 'Asia/Shanghai',
  'Qingdao': 'Asia/Shanghai',
  'Dalian': 'Asia/Shanghai',
  'Harbin': 'Asia/Shanghai',
  'Guilin': 'Asia/Shanghai',
  'Kunming': 'Asia/Shanghai',
  'Lijiang': 'Asia/Shanghai',
  'Lhasa': 'Asia/Shanghai',
  'Urumqi': 'Asia/Urumqi',

  'Taipei': 'Asia/Taipei',
  'Kaohsiung': 'Asia/Taipei',
  'Taichung': 'Asia/Taipei',

  'Macau': 'Asia/Macau',

  'Ulaanbaatar': 'Asia/Ulaanbaatar',
  'Pyongyang': 'Asia/Pyongyang',

  // ==========================================
  // CENTRAL ASIA (15+ cities)
  // ==========================================
  'Almaty': 'Asia/Almaty',
  'Astana': 'Asia/Almaty',
  'Tashkent': 'Asia/Tashkent',
  'Samarkand': 'Asia/Samarkand',
  'Bukhara': 'Asia/Samarkand',
  'Bishkek': 'Asia/Bishkek',
  'Dushanbe': 'Asia/Dushanbe',
  'Ashgabat': 'Asia/Ashgabat',
  'Baku': 'Asia/Baku',
  'Tbilisi': 'Asia/Tbilisi',
  'Yerevan': 'Asia/Yerevan',

  // ==========================================
  // OCEANIA (30+ cities)
  // ==========================================
  'Sydney': 'Australia/Sydney',
  'Melbourne': 'Australia/Melbourne',
  'Brisbane': 'Australia/Brisbane',
  'Perth': 'Australia/Perth',
  'Adelaide': 'Australia/Adelaide',
  'Gold Coast': 'Australia/Brisbane',
  'Canberra': 'Australia/Sydney',
  'Hobart': 'Australia/Hobart',
  'Darwin': 'Australia/Darwin',
  'Cairns': 'Australia/Brisbane',
  'Newcastle': 'Australia/Sydney',
  'Sunshine Coast': 'Australia/Brisbane',
  'Byron Bay': 'Australia/Sydney',
  'Great Barrier Reef': 'Australia/Brisbane',
  'Uluru': 'Australia/Darwin',

  'Auckland': 'Pacific/Auckland',
  'Wellington': 'Pacific/Auckland',
  'Christchurch': 'Pacific/Auckland',
  'Queenstown': 'Pacific/Auckland',
  'Rotorua': 'Pacific/Auckland',

  'Fiji': 'Pacific/Fiji',
  'Suva': 'Pacific/Fiji',
  'Tahiti': 'Pacific/Tahiti',
  'Bora Bora': 'Pacific/Tahiti',
  'Guam': 'Pacific/Guam',
  'Samoa': 'Pacific/Apia',
  'Tonga': 'Pacific/Tongatapu',
  'Vanuatu': 'Pacific/Efate',
  'New Caledonia': 'Pacific/Noumea',
  'Papua New Guinea': 'Pacific/Port_Moresby',
  'Solomon Islands': 'Pacific/Guadalcanal',
  'Palau': 'Pacific/Palau',
  'Marshall Islands': 'Pacific/Majuro',
  'Kiribati': 'Pacific/Tarawa',
  'Micronesia': 'Pacific/Pohnpei',
  'Cook Islands': 'Pacific/Rarotonga',
  'Norfolk Island': 'Pacific/Norfolk'
};

// Get sorted list of city names
window.getTimezoneCityNames = function() {
  return Object.keys(window.TimezoneCities).sort();
};

// Search cities by name
window.searchTimezoneCities = function(query) {
  if (!query) return [];
  const lowerQuery = query.toLowerCase();
  return Object.keys(window.TimezoneCities)
    .filter(city => city.toLowerCase().includes(lowerQuery))
    .sort();
};

console.log(`✅ Timezone database loaded: ${Object.keys(window.TimezoneCities).length} cities`);
